### ISSUE TITLE
Combined heavy Stdio and Socket IO crashes the VM

### ISSUE THREAD

**Issue by akgrant43** [guillep/pharo-core#11796]
**Bug description**
The VM can crash with an access violation on linux when there is simultaneous Stdio and Socket IO.  This can happen at any time, but requires heavy load to trigger reliably.

**To Reproduce**

The test harness in which we reproduced and fixed this isn't easily transferrable, however the sequence of events is fairly clear...

The last action of `aio_handle_events()` is to iterate over all file descriptors to check for IO and hand it off to the handler.  However the `for` loop starts with `fd=0`, which means that it includes the Stdio file descriptors, but the `clientData[]` for the these file descriptors is not set up, so that if there is simultaneous Stdio and Socket IO, when `handler(fd, clientData[fd], AIO_xxx)` is called it then calls `dataHandler(fd, *data, *flags)` from `SocketPluginImpl.c` and the first `logTrace()` crashes with an access violation since data = 0.

Information from a gdb session is included below.

**Expected behavior**
All IO completes successfully and the VM doesn't crash.

**Screenshots**
The gdb session describing the crash is included below.

**Version information:**
 - OS: Ubuntu
 - Version: 22.04
 - Pharo Version: 10

**Expected development cost**

The crash can be avoided by not processing file descriptors for which the clientData isn't configured, i.e. change the start of the loop (line 299) to be:

```
        for (fd = 0; fd < maxFd; ++fd) {
        aioHandler handler;
        
        if (clientData[fd] == 0) continue;

        //_DO_FLAG_TYPE();
        //_DO(AIO_R, rd)
        if (FD_ISSET(fd, &rd)) {
```

The real solution is probably to initialise `wrHandler[]` with `undefinedHandler` instead of `dataHandler` for fd 0.  But it would be good for someone else with more knowledge of this module to confirm.

Other possible solutions are to start the loop with a higher initial value for `fd`, probably 16, but it isn't clear to me what the correct value would be.

**Additional context**

The test harness we set up has Pharo acting as a server and connecting 1500 clients to it, responding to requests and logging activity to the console.

Running Pharo under gdb and triggering the issue results in:

```
Thread 1 "GlamorousToolki" received signal SIGSEGV, Segmentation fault.
0x00007ffff240c3e8 in dataHandler (fd=0, data=0x0, flags=4) at extracted/plugins/SocketPlugin/src/common/SocketPluginImpl.c:591
591	  logTrace("dataHandler(%d=%d, %p, %d)\n", fd, pss->s, data, flags);
(gdb) 


(gdb) bt
#0  0x00007ffff240c3e8 in dataHandler (fd=0, data=0x0, flags=4)
    at extracted/plugins/SocketPlugin/src/common/SocketPluginImpl.c:591
#1  0x00007ffff712235b in aio_handle_events (microSeconds=50000)
    at extracted/vm/src/unix/aio.c:314
#2  0x00007ffff7121cde in aioPoll (microSeconds=50000)
    at extracted/vm/src/unix/aio.c:216
#3  0x00007ffff711ce25 in ioRelinquishProcessorForMicroseconds (microSeconds=50000)
    at extracted/vm/src/common/heartbeat.c:307
#4  0x00007ffff70effd1 in primitiveRelinquishProcessor ()
    at generated/64/vm/src/cointerp.c:35534
#5  0x000000002c789c76 in  ()
#6  0x00007ffff5701640 in  ()
#7  0x000000002de5b190 in  ()
#8  0x0000000100000000 in  ()
#9  0x000000002e163a50 in  ()
#10 0x00007fffffff6180 in  ()
#11 0x00007ffff70720e0 in interpret ()
    at generated/64/vm/src/cointerp.c:2978


(gdb) list
586	/* read or write data transfer is now possible for the socket. */
587	
588	static void dataHandler(int fd, void *data, int flags)
589	{
590	  privateSocketStruct *pss= (privateSocketStruct *)data;
591	  logTrace("dataHandler(%d=%d, %p, %d)\n", fd, pss->s, data, flags);
592	
593	  if (pss == NULL)
594	    {
595	      logTrace("dataHandler: pss is NULL fd=%d data=%p flags=0x%x\n", fd, data, flags);


(gdb) print data
$1 = (void *) 0x0
(gdb) print pss
$2 = (privateSocketStruct *) 0x0


(gdb) up
#1  0x00007ffff712235b in aio_handle_events (microSeconds=50000)
    at extracted/vm/src/unix/aio.c:314
314	            handler(fd, clientData[fd], AIO_W);
(gdb) list
309	        }
310	        //_DO(AIO_W, wr)
311	        if (FD_ISSET(fd, &wr)) {
312	            handler = wrHandler[fd];
313	            FD_CLR(fd, &wrMask);
314	            handler(fd, clientData[fd], AIO_W);
315	            wrHandler[fd]= undefinedHandler;
316	        }
317	        //_DO(AIO_X, ex)
318	        if (FD_ISSET(fd, &ex)) {


(gdb) print fd
$3 = 0
(gdb) print clientData[fd]
$4 = (void *) 0x0
(gdb) print wrHandler[fd]
$5 = (aioHandler) 0x7ffff240c3a0 <dataHandler>

```

**Comment by akgrant43** [comment]
This issue can't be fixed properly with the suggestions above.  A new issue will be opened.
